//
// Created by lukas on 04.06.15.
//

#ifndef ITP4_CONSTANTS_H
#define ITP4_CONSTANTS_H

enum class States {STATE_IDLE, STATE_SELECTED, STATE_MOVING, STATE_FIGHT };
enum class InputEvent {EVENT_LEFTCLICK = 0, EVENT_RIGHTCLICK = 1, EVENT_MIDDLECLICK = 2};


#endif //ITP4_CONSTANTS_H
